version: '3'
services:
  merchant-service:
    build: ./merchant
    ports:
      - "50051:50051"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=50051
      - SERVICE_IP_VERSION=4
    networks:
      - internalnetwork

  rate-limiter-service:
    build: ./ratelimiter
    ports:
      - "50052:50052"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=50052
      - SERVICE_IP_VERSION=4
      - MERCHANT_SERVICE_HOST=merchant-service
      - MERCHANT_SERVICE_PORT=50051
    networks:
      - internalnetwork

  ledger-service:
    build: ./ledger
    ports:
      - "50053:50053"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=50053
      - SERVICE_IP_VERSION=4
    networks:
      - internalnetwork

  bank-simulator:
    build: ./bank
    environment:
      - PAYMENT_GATEWAY_HOST=payment-api-service
      - PAYMENT_GATEWAY_PORT=8080
    expose:
      - "8000"
    networks:
      - banknetwork

  payment-api-service:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - SERVICE_IP_VERSION=4
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8080
      - MERCHANT_SERVICE_HOST=merchant-service
      - MERCHANT_SERVICE_PORT=50051
      - RATE_LIMITER_SERVICE_HOST=rate-limiter-service
      - RATE_LIMITER_SERVICE_PORT=50052
      - LEDGER_SERVICE_HOST=ledger-service
      - LEDGER_SERVICE_PORT=50053
      - BANK_SIMULATOR_HOST=bank-simulator
      - BANK_SIMULATOR_PORT=8000
    networks:
      - internalnetwork
      - externalnetwork
      - banknetwork

  merchant-ui-service:
    build: ./merchant-ui
    ports:
      - "3000:3000"
    environment:
      - PAYMENT_GATEWAY_HOST=payment-api-service
      - PAYMENT_GATEWAY_PORT=8080
    networks:
      - externalnetwork

networks:
  externalnetwork:

  internalnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/29
    # internal: true

  banknetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.21.21.0/29
    # internal: true